name: Android build CI
on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        run: |
          echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
      - name: prebuilt
        run: |
          sed -i -e '/appcenter/d' app/build.gradle.kts
          sed -i -e '/Analytics.trackEvent(Constants/d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/LibReferenceFragment.kt
          sed -i -e '/isAnonymousAnalyticsEnabled/,+5d' app/src/main/kotlin/com/absinthe/libchecker/LibCheckerApp.kt
          sed -i -e '/Analytics.trackEvent/,+3d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/snapshot/SnapshotFragment.kt
          sed -i -e '/Analytics.trackEvent/,+3d' app/src/main/kotlin/com/absinthe/libchecker/ui/detail/SnapshotDetailActivity.kt
          sed -i -e '/Constants.Event.EASTER_EGG/d; /Renge 10 hits/,+1d' app/src/main/kotlin/com/absinthe/libchecker/ui/about/AboutActivity.kt
          sed -i -e '/Analytics.trackEvent/,+5d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/LibReferenceFragment.kt
          sed -i -e '/microsoft/d; /AppCenter/d; /Analytics/d; /Crashes/d' app/src/main/kotlin/com/absinthe/libchecker/LibCheckerApp.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/about/AboutActivity.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/detail/SnapshotDetailActivity.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/applist/AppListFragment.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/settings/LibThresholdDialogFragment.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/settings/SettingsFragment.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/statistics/LibReferenceFragment.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/main/MainActivity.kt
          sed -i -e '/microsoft/d; /EventProperties/d; /Analytics/d' app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/snapshot/SnapshotFragment.kt
          sed -i -e '/microsoft/d; /Analytics.trackEvent/d' app/src/main/kotlin/com/absinthe/libchecker/viewmodel/HomeViewModel.kt
      - name: Build with Gradle
        run: |
          bash ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v2
        with:
          path: "app/build/outputs/apk/release/*-signed.apk"
      - name: Send commit to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |+
            New push to github!
            *${{ github.event.head_commit.message }}* by ${{ github.event.head_commit.author.name }}
            See commit detail [here](${{ github.event.head_commit.url }})
          document: "app/build/outputs/apk/release/*-signed.apk"
