#更新fork
name: update fork

on: 
  schedule:
    - cron: "0 0 * * *" #设置定时任务

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: bdougie/fetch-upstream@master
      with:
        upstream: zhaobozhen/LibChecker
